export const booksellers = [
    'Dunton, John',
    'Creech, William',
    'Halm, Friedrich',
    'Tonson, Jacob',
    'Gebauer, Johann Justinus',
    'Brill, Johannes',
    'Blum, Robert',
    'Zunkel, Heinrich Gottfr.',
    'Benziger, Louise',
    'Fuhri, Koenraad',
    'Fennitzer, Johann',
    'Albrecht, Johann',
    'Feyerabend, Sigmund',
    'Phillips, William',
    'Eyraud, Hermann',
    'Koehler, Karl Franz',
    'Tauchnitz, Karl Christian Philipp',
    'Ploos van Amstel, Cornelis',
    'Hitzig, Julius Eduard',
    'Keferstein, Albrecht Ludwig',
    'Fokke, Simon',
    'Braun, Kaspar',
    'Edelmann, Alexander',
    'Kilian, Wolfgang Philipp',
    'Schulze, Theodor',
    'Artaria, Jean Marie',
    'Panzer, Georg Wolfgang',
    'Platter, Thomas',
    'Ramsay, Allan',
    'Debure, Jean-Jacques',
    'Wirz, Philipp',
    'Weigel, Felix Oswald',
    'Klinkhardt, Julius',
    'Egenolff, Christian',
    'Baer, Joseph Abraham',
    'Hecking, Gottfried',
    'Wever, Arnold',
    'Sporschil, Johann',
    'Weiss, Charles',
    'Eikelenberg, Simon',
    'Bittorf, Christian Benjamin',
    'Luchtmans, Samuel',
    'Cassell, John',
    'Meyer, Gustav',
    'Hutton, William',
    'Bennett, James Gordon',
    'Hoffmann, Karl',
    'Gropius, George',
    'Caulfield, James',
    'Voerster, Carl Friedrich',
    'Mechetti, Pietro',
    'Herbert, William',
    'Johann Christoph',
    'Uri, Samson',
    'Gleditsch, Maria',
    'Bli√ümer, David',
    'Simion, Leonhard',
    'Hierta, Lars Johan',
    'Schelte, Dirk',
    'Ehlermann, Erich',
    'Nijhoff, Paulus',
    'Benziger, Ursula',
    'Dietzel, Friedrich Elias',
    'Priolo, Benjamin',
    'Hollis, Thomas',
    'Cribb, Robert',
    'Gau√ü, Carl Friedrich',
    'Nijhoff, Martinus',
    'Bracke, Wilhelm',
    'Hitchcock, DeWitt C.',
    'Mauke, Johann Heinrich Wilhelm',
    'Tauber, Johann',
    'Roennagel, Johann Wilhelm',
    'Bryant, John Frederick',
    'Hummel, Leonard',
    'Graves, Richard',
    'Endter, Peter Friedrich',
    'Alfonso',
    'Wappler, Christian Friedrich',
    'Du Mont, Marcus',
    'Hartmann, Johann',
    'Hartmann, Bernhard',
    'Brockhaus, Friedrich',
    'Chandler, Samuel',
    'Bulifon, Antonio',
    'Marcolini, Francesco',
    'Breitkopf, Christoph Gottlob',
    'Weber, Hermann',
    'Dieterich, Heinrich',
    'Wedel, Benjamin',
    'Lambeck, Peter',
    'Braun, Johann Friedrich',
    'Cotta, Johann Georg',
    'Pelz, Eduard',
    'Hildenbrandt, Samuel',
    'Dodsley, Robert',
    'Seidel, Ludwig Wilhelm',
    'Heerdegen, Friedrich',
    'Rockwell, Horace Tyler',
    'Heitz, Paul',
    'Dodd, Thomas',
    'Friedrich Wilhelm',
    'Ackermann, Albin',
    'Hebbel, Friedrich',
    'Gryphius, Sebastianus',
    'Bode, Johann Joachim Christoph',
    'Castorf, Heino',
    'Portielje, Gerrit',
    'Stieff, Christian',
    'Gerold, Carl',
    'Boydell, John',
    'Hain, Melchior Gottfried',
    'Teubner, Johann Michael',
    'Berends, Julius',
    'Hanke, Martin',
    'Sulpke, C. G.',
    'Tessaro, Angelo',
    'Martinet, Aaron',
    'Lynch, William',
    'Wucherer, Georg Philipp',
    'Lehmann, Georg',
    'Gleditsch, Johann Friedrich',
    'Thiboust, Claude Louis',
    'Arnz, ..',
    'Weinmann, Hans Conrat',
    'Engelbrecht, Christian',
    'Bermann, Joseph',
    'Querini, Angelo Maria',
    'Ellmenreich, Friedrich Wilhelm',
    'Bertuch, Friedrich Justin',
    'Bolingbroke, Henry St. John',
    'Maske, Ludwig Ferdinand',
    'Meyssens, Joannes',
    'Campe, Friedrich',
    'Gyldendal, S√łren',
    'Thanner, Jacob',
    'Peypus, Friedrich',
    'Engelmann, Godefroy',
    'Kuehtze, Paul',
    'Longman, Thomas Norton',
    'Sadeler, Jan',
    'Fliedner, Theodor',
    'Walter, John',
    'Smirdin, Aleksandr F.',
    'Gaubisch, Urban',
    'Bohn, Hermann',
    'Baines, Edward',
    'Felsecker, Johann Jonathan',
    'Krantz, Gottlob',
    'Bermann, Anna',
    'Naumann, Ernst Theodor',
    'Goeree, Willem',
    'Bill, Anna',
    'Kuhlmey, Joh. Fried.',
    'Loescher, Hermann',
    'Pierer, Heinrich August',
    'Franklin, Benjamin',
    'Prestel, Maria Katharina',
    'Greve, Ernst Wilhelm',
    'Gerdes, Christian',
    'Rhau, Georg',
    'Appleton, Daniel',
    'Tieboel, Jacob',
    'Fenitzer, Johann',
    'Boissard, Jean Jacques',
    'Benziger, Louis',
    'Felwinger, Hanns',
    'Herz, Georg',
    'Sacco, Albert',
    'Homann, Johann Baptist',
    'Senefelder, Alois',
    'Kilian, Philipp Andreas',
    'Wendler, Christoph Gottfried',
    'Weigel, Johann August Gottlob',
    'Schulz, David',
    'Leigh, George',
    'Biscioni, Antonio Maria',
    'Ritter, Christian',
    'Fischer, H.',
    'Bodenehr, Gabriel',
    'Dyer, George',
    'Kimmelmann, Georg',
    'Mieser, Jacob',
    'Manuzio, Aldo Pio',
    'Zunkel, Imm.',
    'Springer, Ferdinand',
    'Manuzio, Paolo',
    'Nijgh, H.',
    'Dannheimer, Tobias',
    'Goltzius, Hubert',
    'Olearius, Adam',
    'Keinz, Friedrich',
    'Lackington, James',
    'Leiner, Oskar',
    'Thurneysser zum Thurn, Leonhardt',
    'Kissling, Johann',
    'Hempel, Gustav',
    'Cosimo',
    'Radink, Jacobus',
    'Henze, Adolf',
    'Thomson, James',
    'Raspe, Gabriel Nikolaus',
    'Schott, Johann Andreas',
    'Birckmann, Johann',
    'Roper, Abel',
    'Becker, J. H.',
    'Bernstein, Gerson',
    'Baskerville, John',
    'Cruden, Alexander',
    'Ehinger, Elias',
    'Hetzel, Pierre-Jules',
    'Westermann, Friedrich',
    'Klette, Anton',
    'Sartorius, David',
    'Gerhard, Christoph',
    'Schenk, Pieter',
    'Fisher, ...',
    'Duim, Frederik',
    'Franz, Johann Michael',
    'Bulmer, William',
    'Heinrich, Severin',
    'Goltzius, Hendrick',
    'N.',
    'Battmann, Ludwig',
    'Rost, Christian Friedrich Adolf',
    'Agricola, Conrad',
    'Vieweg, Friedrich',
    'Engelbrecht, Martin',
    'Daubmann, Hans',
    'Nolte, Gustav Eduard',
    'Constable, Archibald',
    'Jaeger, Balthasar',
    'Gamba, Bartolommeo',
    'Lehmann, Julius Friedrich',
    'Hase, Gottlob Friedrich',
    'Neumann, Paul',
    'Cosmar, Alexander',
    'Speckter, Johann Michael',
    'Barthel, Christophorus',
    'Fabricius, Simon',
    'Francke, August Hermann',
    'Doll, Anton',
    'Hinstorff, Carl',
    'Gleditsch, Johann Gottlieb',
    'Zarncke, Friedrich',
    'Schneider, Adam Gottlieb',
    'Oncken, Johann Gerhard',
    'Du Mont, Joseph',
    'Sebald, Christoph Adam',
    'Ro√überg, Ludwig',
    'Kaiser, Hermann',
    'Kraus, Johann Ulrich',
    'Eyraud, Carl August',
    'Jacobus',
    'Love, John',
    'Pascheles, Wolf',
    'Lochner, Johann Christoph',
    'Mann, Margaretha Magdalena',
    'Zieger, Johann',
    'Roth-Scholtz, Friedrich',
    'Wigand, Otto',
    'Baedeker, Karl',
    'Appleton, William Henry',
    'Haslinger, Carl',
    'Hanfstaengl, Franz',
    'Smellie, William',
    'Kilian, Lucas',
    'Zunner, Johann Conrad',
    'Kleemann, Christian Friedrich Carl',
    'Sanson, Nicolas',
    'Atkinson, Thomas',
    'Trewendt, Eduard',
    'Krause, Richard',
    'Strobel, Johann Baptist',
    'Berendsohn, B. S.',
    'Biagosch, Heinrich',
    'Brune, Guillaume-Marie-Anne',
    'Leede, Christian Friedrich Erdmann',
    'Lutze, Arthur',
    'Nulandt, F. Louis',
    'Winterschmid, ...',
    'Keil, Ernst',
    'Pesne, Antoine',
    'Manuel, Jacques Antoine',
    'Magliabechi, Antonio',
    'Knight, Charles',
    'Blok, David',
    'Heubel, Ludwig Karl',
    'Camphuysen, Dirk Rafaelszoon',
    'Campe, Heinrich Wilhelm',
    'Kammerer, Jean Georges',
    'Beyer, Ottomar',
    'Deuticke, Franz',
    'Blaeu, Willem Janszoon',
    'Tauchnitz, Bernhard',
    'Adler, Carl',
    'Goedecke, Gustav',
    'Eisenmann, Ernst',
    'Breitkopf, Bernhard Christoph',
    'Harper, Joseph Wesley',
    'Gessner, Christian Friedrich',
    'Masson, Antoine',
    'Pauli, Joachim',
    'Lempertz, Mathias',
    'Ebner, Jacob Friedrich',
    'Menno',
    'Takke, Heinrich Christoph',
    'Arrhenius, Johan Petter',
    'Maittaire, Michael',
    'Breitkopf, Johann Gottlob Immanuel',
    'Holze, Gottlob',
    'Zimmermann, Gottfried',
    'Kirchhoff, Albrecht',
    'Hess, Felix',
    'Heidegger, Heinrich',
    'Froben, Johann',
    'Vogel, Friedrich Christian Wilhelm',
    'Bode, Johann Elert',
    'Ebner von Eschenbach, Carl Wilh.',
    'Huber, Jacques',
    'Starter, Jan Janszoon',
    'Schreck, Heinrich Ludwig August',
    'Janin, Jules Gabriel',
    'Koerten, Frans',
    'Appleton, Daniel Sidney',
    'Loosjes, Jakob',
    'Tyroff, Konrad',
    'Isselburg, Peter',
    'Bassermann, Friedrich Daniel',
    'Dupuy, Pierre',
    'Helwing, Clemens',
    'Sellier, Arthur',
    'Minderlein, Mathias',
    'Helmert, ...',
    'Voigt-Diederichs, Helene',
    'Galle, Theodoor',
    'Jaillot, Alexis Hubert',
    'Kretzschmar, Gustav Adolph',
    'Koehler, Woldemar',
    'Hartwig, Theodor',
    'Springer, Julius',
    'Bosch, Matheus van Heyningen',
    'Palm, Johann Philipp',
    'Jaeger, Johann Wilhelm Abraham',
    'Richter, Ferdinand Jacob',
    'Elers, Heinrich Julius',
    'Schulthess, Friedrich',
    'Cave, Edward',
    'Gleditsch, Anna Magdalena',
    'Voss, Leopold',
    'Badius Ascensius, Jodocus',
    'Brahe, Tycho',
    'Walker, John',
    'Fleischmann, Johann Michael',
    'Gubrynowicz, WŇāadysŇāaw Ludwik',
    'Jones, John Paul',
    'Unckel, Johann Karl',
    'Kretschmann, Karl Gottfried',
    'Gleditsch, Johann Ludwig',
    'Horatius Flaccus, Quintus',
    'Capaun-Karlowa, Friedrich',
    'Serig, Carl Friedrich',
    'Volkmann, Wilhelm',
    'Miller, William',
    'Thieme, Herman Carel Anton',
    'Uylenbroek, Pieter Johannes',
    'Laurens, Henry',
    'Klinkhardt, Bruno',
    'Grunow, Johannes',
    'Lauer, David',
    'Baedeker, Gottschalk Dietrich',
    'Hentze, Friedrich',
    'Anderson, William',
    'Raphelengius, Franciscus',
    'Papillon, Jean-Michel',
    'Staedel, Josias',
    'Schultze, Hermann',
    'Einhorn, Friedrich Wilhelm',
    'Ptolemaeus, Claudius',
    'Kopernikus, Nikolaus',
    'Oldenbourg, Rudolf',
    'Manuel, Louis-Pierre',
    'Blackie, John',
    'Gastl, Johann Georg',
    'Hallervord, Martin',
    'Schwabe, Johann Joachim',
    'Andreae, Johann Philipp',
    'Aratus',
    'Demuth, Theodor',
    'Norstedt, Carl',
    'Perry, James',
    'Brigl, Bernhard',
    'Gaspar Maristany, Josep',
    'Franke, Heinrich',
    'Upton, James',
    'Malling, P. T.',
    'Meyer, Hans',
    'Quentell, Arnold',
    'Scamozzi, Vincenzo',
    'Macarez, Alphonse',
    'Kilian, Georg',
    'Boerner, Johann Andreas',
    'Frauenholz, Johann Friedrich',
    'Marshoorn, Gerard',
    'Klein, Hans',
    'Palm, Christoph Ludwig',
    'Barnum, Phineas Taylor',
    'Staats, August',
    'Clausel de Coussergues, Jean-Claude',
    'Mentelin, Johann',
    'Pfautz, Christoph',
    'Lotter, Melchior',
    'Kramer, Johann',
    'Faber, Johann Adam',
    'Bielefeld, Joseph',
    'Blumauer, Alois',
    'Volta, Alessandro',
    'Weber, Johann Jakob',
    'Duval, Valentin Jameray',
    'Endter, Michael',
    'Harper, James',
    'Eggestein, Heinrich',
    'Heyer, Georg Friedrich',
    'Novikov, Nikolaj I.',
    'Reich, Rudolf',
    'Hirzel, Salomon',
    'Langhoff, E. F. L.',
    'Welcker, Karl Theodor',
    'Black, Adam',
    'Barba, Jean Nicolas',
    'Duncker, Carl',
    'Schramm-Macdonald, Hugo',
    'Peetz, Johann Conrad',
    'Guy, Thomas',
    'Hoffmann, Johann',
    'Anselm Casimir',
    'Harper, John',
    'Gering, Ulrich',
    'Galpin, Thomas Dixon',
    'Schneider, Georg Jacob',
    'Schlawitz, Gustav',
    'Campe, Joachim Heinrich',
    'Wilhelm, Matthias',
    'Reinhardt, Ernst',
    'Glasser, Leonhard',
    'Picart, Bernard',
    'Frommann, Eduard',
    'Stiller, Karl Christoph',
    'Schad, Joseph',
    'Westermann, Bernhard',
    'Korabinsky, Johann Matthias',
    'Desessarts, Nicolas Toussaint Lemoyne',
    'Ritzsch, Gregorius',
    'Terres',
    'Nestler, Friedrich Hermann',
    'Wolf, Peter Philipp',
    'Schulze, Ernst Heinrich Christoph',
    'Yver, Jan',
    'Berner, Johann',
    'Korn, Julius',
    'Panckoucke, Charles Joseph',
    'Blaeu, Joan',
    'Ukert, Friedrich August',
    'Holst, Johann',
    'Liesching, Friedrich',
    'Helm, Friedrich August',
    'Braun, Johann Philipp',
    'Niethammer, Albert',
    'Hazich, Johann',
    'Klein, Max',
    'Miesser, Christoph',
    'Hazeu, Johannes Corneliszoon',
    'Meidinger, Hermann Joseph',
    'Lentz, Hieronymus',
    'Miller, Thomas',
    'Libri, Guillaume',
    'West, James',
    'Hittorp, Gottfried',
    'Trautner, Daniel',
    'Kirgate, Thomas',
    'Fehr, Friedrich Eugen',
    'Enke, Ferdinand Ernst Jakob',
    'Klasing, Otto',
    'Artaria, Karl',
    'Jebens, Ernst Heinrich Christoph',
    'Brill, Evert Jan',
    'Eberhard, Johann August',
    'Muller, P. R. D.',
    'Weigel, Rudolph',
    'Barth, Wilhelm Ambrosius',
    'Platter, Felix',
    'Caffart, Jean',
    'Baker, Henry',
    'Schlesinger, Marcus',
    'Schulz, Otto August',
    'Sadeler, Raphael',
    'Merian, Maria Sibylla',
    'Abraham, Max',
    'Mahncke, Georg Heinrich',
    'Gerlach, Johann Christoph Friedrich',
    'Klosemann, Kaspar',
    'Arnz, Heinrich',
    'Ruge, Arnold',
    'Lavater, Johann Caspar',
    'Weigel, Christoph',
    'Keay, Henry William',
    'Hirth, Georg',
    'Merian, Matthaeus',
    'Crusius, Siegfried Leberecht',
    'Kilian, Georg Christoph',
    'Koenig, Friedrich',
    'Wahlstab, Bernhard Gotthard',
    'Hass, Johann',
    'Voigt, Bernhard Friedrich',
    'Schupfel, Lorenz',
    'Barnes, Alfred Smith',
    'Schmidmaier von Schwarzenbruck, Johann Jobst',
    'Wigand, Georg',
    'Brockhaus, Heinrich Eduard',
    'Grafton, Richard',
    'Michaud, Joseph Fr.',
    'Weigel, Magdalena Esther',
    'Rumpf, Christoph Friedrich',
    'Rautenberg, Carl Ludwig',
    'Halbmaier, Simon',
    'Hennings, Wilhelm',
    'Beger, Lorenz',
    'Heyns, Zacharias',
    'Pfeil, Heinrich',
    'Tempsky, Friedrich',
    'Enslin, Theodor Christian Friedrich',
    'Westermann, Georg',
    'Galilei, Galileo',
    'Bermann, Johann Sigmund',
    'Manuel, Niklaus',
    'Waldow, Alexander',
    'Scherff, Balthasar',
    'Kloss, Johann Herbord',
    'Spamer, Otto',
    'Bell, Andrew',
    'Kretschmann, Jeremias',
    'Merseburger, Johann Joachim Erdmann',
    'Ackermann, Christian Georg',
    'Preston, William',
    'Nichols, John',
    'Panzer, Georg Wolfgang Franz',
    'Chambers, Robert',
    'Cholin, Maria Elisabetha',
    'Elzevier, Matthijs',
    'Seiffart, Christian Gottlieb',
    'Osiander, Christian Friedrich',
    'Tempest, Pierce',
    'Asher, Adolf',
    'Endter, Balthasar Joachim',
    'Kre√ü, Jonas Paulus',
    'Grapheus, Cornelius',
    'Heinsius, Daniel',
    'Appleton, George Swett',
    'Merseburger, Otto',
    'Duncker, Franz Gustav',
    'Blum, Jenny',
    'Reimer, Georg Andreas',
    'Tross, Edwin',
    'Hilden, Wilhelm',
    'Harper, Fletcher',
    'Miklosich, Franz',
    'Klasing, August',
    'Schumann, August',
    'Kirchner, Ernst',
    'Kohles, Jobst Wilhelm',
    'Lufft, Hans',
    'Immerzeel, Johannes',
    'Herz, Johann Daniel',
    'Marucelli, Francesco',
    'Salzmann, Christian Gotthilf',
    'Schelhorn, Johann Georg',
    'Lang, Johann Baptist',
    'Hahn, Heinrich Wilhelm',
    'Schwetschke, Karl Gustav',
    'Tullenton, ...',
    'Freher, Paul',
    'Weinberger, Josef',
    'Fickler, Joseph',
    'Hellwig, Ferdinand',
    'Bossange, Martin',
    'Vieweg, Heinrich',
    'Pfeifer, Ferdinand',
    'Bleul, Peter Paul',
    'Frobenius, Heinrich',
    'Stilke, Hermann',
    'Marx, Eugen',
    'Steiger, Ernst',
    'Endter, Johann Andreas',
    'Newton, Isaac',
    'Mylius, Arnold',
    'Neumann, Paul Julius',
    'Holzhausen, Adolf',
    'Tessari, ...',
    'Gruterus, Janus',
    'Verbruggen, J. W.',
    'Asperne, James',
    'Prinz, August',
    'Bril, Jakob',
    'Elzevir, Daniel',
    'Ferstl, Franz',
    'Scapin, Carlo',
    'Richardson, Samuel',
    'Richter, Ludwig',
    'Perles, Moritz',
    'Gaspar Maristany, Ferran',
    'Gaedicke, Johann Christian',
    'Endter, Georg',
    'Schipper, Jan Jansz.',
    'Kummer, Paul Gotthelf',
    'Siegismund, Karl',
    'Bardi, Luigi',
    'Arnst, Friedrich',
    'Krug, Georg Friedrich Lorenz',
    'Berner, Conrad',
    'Franckh, Friedrich Gottlob',
    'Tyroff, Johann David',
    'Schierbeek, Roelof Jacob',
    'Klinkicht, Christian Ehregott',
    'Zimmermann, Johann Christoph',
    'Cnobloch, Karl',
    'Felsecker, Wolfgang Eberhard',
    'Spittler, Christian Friedrich',
    'Schrag, Johann Wolfgang Eduard',
    'Pomba, Giuseppe',
    'Schlagenhauff, Johann Daniel',
    'Le Clerc, Charles Guillaume',
    'Somer, Jan Pietersz.',
    'Wirz, Hans Konrad',
    'Guthrie, John',
    'Schumacher, Johann Nepomuk',
    'Wight, John',
    'Dupuy, Jacques',
    'Hoffmann, Wilhelm',
    'Bielke, Johann',
    'Canzi, Katharina',
    'Mudie, Charles Edward',
    'Geissel, ...',
    'Credner, Hermann',
    'Mann, C. G.',
    'Moretus, Balthasar',
    'Hunin, Joseph',
    'Verbeyst, Jan Baptist',
    'Korn, Johann Gottlieb',
    'Bruckmann, Friedrich',
    'Albrecht, Christoph',
    'Kuranda, Ignaz',
    'Klein, Hermann J.',
    'Struve, Burkhard Gotthelf',
    'Ernesti, Johann Heinrich Gottfried',
    'Vollsack, Paul Robert',
    'Hirsch, August',
    'Wichern, Johann Hinrich',
    'Milton, John',
    'Augustus Frederick',
    'Tauber, Johann Daniel',
    'Gleerup, Christian Wilhelm Kyhl',
    'Henning, Veit Balthasar',
    'Trutebul, Ludwig',
    'Caxton, William',
    'Steen, Christian',
    'Gleichmann, Hans',
    'Mayer, Carl',
    'Winter, Christian Friedrich',
    'Franz, Georg Christoph',
    'Holste, Lukas',
    'Endter, Georg Andreas',
    'Pauli, Louise',
    'Knoch, Georg Markus',
    'Cartwright, William',
    'Christmann, Joseph',
    'Hoffmann, Gustav Adolph',
    'Mathy, Karl',
    'Adelung, Johann Christoph',
    'Panckoucke, Charles Louis Fleury',
    'Krause, Karl',
    'Tode, Johann Clemens',
    'Debure, Marie-Jacques',
    'Blaesing, August',
    'Fleischauer, Johann Georg',
    'Schmidt, Paul',
    'Tietze, Immanuel',
    'Ebner von Eschenbach, Hieronymus Wilhelm',
    'Lermina, Jules',
    'Auer von Welsbach, Alois',
    'Prault, Pierre',
    'Dunst, Johann Michael',
    'Tallien, Jean-Lambert',
    'Cellius, Erhard',
    'Murray, John',
    'Brinkmann, Bernhard',
    'Lochner, Adam',
    'Caymox, Hubert',
    'Lessing, Gotthold Ephraim',
    'Lange, Johann Gottfried',
    'Peterle, Michael',
    'Claye, Jules Alexandre Saturnin',
    'Burchiello, Il',
    'Ruprecht, Carl August Adolf',
    'Paets, Pieter Jacobsz',
    'Bodmer, Johann Jakob',
    'Mattioli, Pietro Andrea',
    'Brice, Andrew',
    'Bierey, Emil',
    'Donaldson, Andrew',
    'Palier, Hendrik',
    'Oomkens, Jan Janszoon',
    'Wollenweber, Adolph',
    'Weyl, Louis',
    'Dost, Friedr.',
    'Celtis, Konrad',
    'Neff, Paul',
    'Wittmann, Jacob',
    'Osterrieth, Albert',
    'Heiberg, Hermann',
    'Jordan, Wilhelm',
    'Baeumler, Georg Daniel',
    'Degen, Joseph Vinzenz',
    'Schede Melissus, Paulus',
    'Kollmann, Carl',
    'Weidmann, Moritz Georg',
    'Alexander, William',
    'Pynson, Richard',
    'Berlacher, Johann',
    'Bamberg, Felix',
    'Leybourn, William',
    'Siegemund, Fritz',
    'Ludwig',
    'Schrey, Jeremias',
    'Lanckisch, Friedrich',
    'Marschall, Peter',
    'Tamsen, Edward J. H.',
    'Schwann, Leonard',
    'Monath, Johann Caspar',
    'Gutenberg, Barbara',
    'Junius, Hadrianus',
    'Mayr, Johann Baptist',
    'Schauenburg, Moritz',
    'Poelsch, Christ. Gotthelf',
    'Hertz, Wilhelm Ludwig',
    'Plantin, Christophe',
    'Schlemmer, Friedrich',
    'Chevillion, Robert',
    'Didot, Firmin',
    'Luzac, Elie',
    'Palliot, Pierre',
    'Apian, Petrus',
    'Brandstetter, Friedrich',
    'Langenscheidt, Gustav',
    'Volckmar, Ludolf Franz Friedrich',
    'Caimox, Balthasar',
    'Spalding, Johann Joachim',
    'Gates, Horatio',
    'Oporinus, Johannes',
    'Friese, Carl Otto',
    'Berger, Albert',
    'Fokke, Arend',
    'Pech, Georg Paul',
    'Boudan, Alexandre',
    'Winckelmann, Johann Christian',
    'Ungnad zu Sonneck, Hans',
    'Becker, Rudolf Zacharias',
    'Novello, Vincent',
    'Holtrop, Willem',
    'Bachem, Karl Aloys Franz',
    'Schorner, Jacob',
    'Loosjes, Adriaan',
    'Diabelli, Anton',
    'Ge√üner, Salomon',
    'Frick, Wilhelm',
    'Moser, Johann Philipp',
    'Diderot, Denis',
    'Heller, Joachim',
    'Itzstein, Johann Adam',
    'Roth-Scholtz, Anna Maria',
    'Schrag, Johann Leonhard',
    'Bergen, Gimel',
    'Anzengruber, Ludwig',
    'Albert, Joseph',
    'Lion, Rudolf',
    'Heberle, Johann M.',
    'Knorr, Georg Wolfgang',
    'Artaria, Domenico',
    'Fennitzer, Michael',
    'Huzard, Jean Baptiste',
    'Othmar, Hans Wolf',
    'Gerold, Moriz',
    'Devrient, Alphonse',
    'Gerold, Friedrich',
    'Giuntini, Francesco',
    'Oertel, Carl Gottlob',
    'Voerster, Alfred',
    'Gardiner, William Nelson',
    'Bono, Casimiro',
    'Raikes, Robert',
    'Geiger, Johann Heinrich',
    'Grosse, Johann',
    'Widmayer, Heinrich',
    'Hearne, Thomas',
    'Hartleben, Konrad Adolf',
    'Kramm, Christiaan',
    'Tauchnitz, Karl',
    'Ludwig, Christian Gottlieb',
    'Geibel, Carl',
    'Mittler, Ernst Siegfried',
    'Lorenz, Ernst Friedrich Vertraugott',
    'Topp, Joh. Luk.',
    'Dunkel, Norbert',
    'Marx, David Raphael',
    'Fust, Johann',
    'Sander, Adolf',
    'Endter, Wolfgang',
    'Krebs, Benjamin',
    'Cotta von Cottendorf, Johann Georg',
    'Fehr, Georg Friedrich August',
    'Griffiths, Ralph',
    'Henning, Christoph Daniel',
    'Rubens, Philippe',
    'Strahan, William',
    'Kilian, Friedrich',
    'Gaertner, Rudolf',
    'Rigaux, Georges',
    'Erasmus, Desiderius',
    'Felsecker, Adam Jonathan',
    'Volkmer, Ottomar',
    'Hoepli, Ulrico',
    'Barth, Johann Ambrosius',
    'Huber, Arnold',
    'Haslinger, Tobias',
    'Le Mercier, Pierre-Augustin',
    'Fennitzer, Peter Paul',
    'Horvath, Karl Christian',
    'Strabel, Carl Heinrich',
    'Foulis, Robert',
    'Zwingli, Ulrich',
    'Childs, George William',
    'Estienne, Robert',
    'Liegel, Eduard',
    'Sewell, John',
    'Cadell, Thomas',
    'Sweerts, Hieronymus',
    'Hase, Friedrich Traugott',
    'Heckenast, Gustav',
    'Kirchbach, Wolfgang',
    'Streck, Engelbert',
    'Giesecke, Hermann',
    'Arnold, Christoph',
    'Washington, George',
    'Flemming, Carl',
    'Engelmann, Wilhelm',
    'Erhard, Heinrich',
    'Smith, William',
    'Martens, Dirk',
    'Fincelius, Christian',
    'Reimer, Georg Ernst',
    'Mackroth, Ad.',
    'Beer, Andreas Paul',
    'Bullmann, Johann Georg',
    'Denis, Michael',
    'Memmel, Johann Kaspar',
    'Mariette, Pierre Jean',
    'Lange, Johann Georg',
    'Priebatsch, Leopold',
    'Hartig, Jan',
    'Aristarchus',
    'Mechetti, Carlo',
    'Goedsche, Friedrich Wilhelm',
    'Schott, Franz',
    'Lehnhold, Carl Ludwig',
    'Musuros, Markos',
    'Meyri, Johann Christian',
    'Meyer, Joseph',
    'Muratori, Lodovico Antonio',
    'Boerner, Paul Erwin',
    'Schroeder, Eduard Heinrich',
    'Wittich, Ludwig Wilhelm',
    'Ogilvie, John Stuart',
    'Leslie, Frank',
    'Brockhaus, Heinrich',
    'Keferstein, Friedrich Wilhelm',
    'Wieland, Johannes',
    'Engelbrecht, ...',
    'Brockhaus, Friedrich Arnold',
    'Hoffmann, Karl Johann',
    'Gregory, Olinthus',
    'Biester, Johann Erich',
    'Kilian, Philipp',
    'Petrejus, Johannes',
    'Gabelsberger, Franz Xaver',
    'Krabbe, Adolph',
    'Coster, Lourens Janszoon',
    'Mercator, Gerhard',
    'Gent, Thomas',
    'Stalling, Margaretha Catherina',
    'Zeh, Johann Eberhard',
    'Fleischauer, Johann Jacob',
    'Koning, Jacobus',
    'Mainberger, Johann Christoph',
    'Fuchs, Charles',
    'Colnaghi, Paul',
    'Perthes, Caroline',
    'Vogel, Wilhelm Ferdinand Theodor',
    'Meinhold, Karl Christian',
    'Hartknoch, Johann Friedrich',
    'Regiomontanus, Johannes',
    'Vincent, Jacques',
    'Coignard, Jean-Baptiste',
    'Hesse, August',
    'Held, Friedrich Wilhelm Alexander',
    'Pratt, Samuel Jackson',
    'Gelen, Sigmund',
    'Stromer, Ulman',
    'Rubens, Peter Paul',
    'Frommann, Georg Heinrich',
    'Bowyer, William',
    'Naumann, Johann',
    'Schmid, Karl',
    'Melle, Julius Friedrich Wilhelm',
    'Frischlin, Nicodemus',
    'Le Soudier, Henri',
    'Mann, Georg Michael',
    'Prestel, Johann Gottlieb',
    'Holzhauser, Christian',
    'Paetel, Elwin',
    'Hittorp, Gertrud',
    'Endter, Johann Michael',
    'Baillet, Adrien',
    'Manz, Hermann',
    'Caslon, William',
    'Ogilby, John',
    'Koberger, Anton',
    'Erpenius, Thomas',
    'Boll, Rafael',
    'Willer, Georg',
    'Growoll, Adolf',
    'Garcke, Louis',
    'Heerdegen, Wolfgang Paul',
    'Otto, Andreas',
    'Winckler, Andreas',
    'Schnorr von Carolsfeld, Julius',
    'Prudhomme, Louis Marie',
    'Elzevier, Adrianus Joannes',
    'Nijhoff, Isaak Anne',
    'Fincelius, Hiob Wilhelm',
    'Coke, William',
    'Pfeffel, Johann Andreas',
    'Richter, David',
    'Weigel, Theodor O.',
    'Coornhert, Dirk Volkertszoon',
    'Hachette, Louis',
    'Mohr, Jakob Christian Benjamin',
    'Oehmigke, Ludwig',
    'Fritsch, Thomas',
    'Berthold, Otto',
    'Wildt, Arthur',
    'Felssecker, Carl',
    'Lauer, Johann',
    'Krafft, Johann',
    'Froschauer, Christoph',
    'Jones, Richard',
    'Knapen, Achille Maximin Philogone',
    'Hauer, Johann',
    'Hirschfeld, Carl Louis',
    'Scheible, Johann',
    'Wingrave, Francis',
    'Bindley, James',
    'Ackermann, Benedicta Anna Sophie',
    'Tyroff, Martin',
    'Frye, Thomas',
    'Groos, Christian Theodor',
    'Andre, Philip H.',
    'Bruylant, Jean Baptiste',
    'Garamond, Claude',
    'Erdmann, Johann Schweyckardt',
    'Flinsch, Ferdinand Traugott',
    'Hofmann, Albert',
    'Heidegger, Johann Heinrich',
    'Manson, John',
    'Diederichs, Eugen',
    'Frommann, Friedrich Johannes',
    'Elzevier, Jan Jacob',
    'Yntema, Jacob',
    'Buschbeck, Ernst',
    'Wolfe, Reyner',
    'Campe, Julius',
    'Schubothe, Johan Heinrich',
    'Oomkens, Jan',
    'Gaj, Ljudevit',
    'Veith, Franz Anton',
    'Wedel, Maria Magdalena',
    'Lange, Eugen Heinrich Julius',
    'Lindenmeyer, Esaias',
    'Eupel, Friedrich August',
    'Nicolai, Friedrich',
    'Jackson, Joseph',
    'Heinrichshofen, Gotthelf Wilhelm Theodor',
    'Endter, Wolfgang Moritz',
    'Paine, Thomas',
    'Reeder, John',
    'Parey, Paul',
    'Geysbeek, Pieter Gerardus Witsen',
    'Coxe, Peter',
    'Wolf, Jeremias',
    'Buchholz, Wilhelm',
    'Schwann, Franz',
    'Felsecker, J. M.',
    'Naumann, Constantin Georg',
    'Duval, Pierre',
    'Perthes, Friedrich Christoph',
    'Schmidhammer, Johann Andreas',
    'Peignot, Gabriel',
    'Sadeler, √Ügidius',
    'Dibdin, Charles',
    'Gubitz, Friedrich W.',
    'Stelter, Johann',
    'Mahlmann, Siegfried August',
    'Fleischer, Friedrich',
    'Endter, Maria',
    'Vieweg, Eduard',
    'Teubner, Benedictus Gotthelf',
    'Schuberth, Julius',
    'Decker, Georg Jakob',
    'Frommann, Carl Friedrich Ernst',
    'Grillparzer, Franz',
    'Lipperheide, Franz',
    'Schniebs, Johann Georg',
    'Le Petit, Denise',
    'Kroh, Franz',
    'Zunckel, Christoph',
    'Steinheil, Carl August',
    'Ritter, Kaspar',
    'Orlers, Jan Janszn.',
    'Coppenol, Lieven Willems',
    'Grosse, Friedrich',
    'Seemann, Ernst A.',
    'Veit, Moritz',
    'Haussmann, Wilhelm',
    'Lebeau, Joseph',
    'Bergen, Christian',
    'Pers, Dirck Pieterszoon',
    'Cranach, Lucas',
    'Enslin, Adolph',
    'Weber, Wilhelm',
    'Heeren, Arnold H. L.',
    'Kaler, Johann',
    'Merk, Johann Konrad',
    'Litolff, Henry',
    'Hoffmeister, Franz Anton',
    'Lipsius, Justus',
    'Kilian, Wolfgang',
    'Roman, Adriaen',
    'Marabini, Edmund',
    'Firmin-Didot, Ambroise',
    'Hegel, Frederik Vilhelm',
    'Hirt, Ferdinand',
    'Grattenauer, Ernst C.',
    'Brockhaus, Albert',
    'Louvet de Couvray, Jean-Baptiste',
    'Beck, Johann Daniel',
    'Chardin, Charles',
    'Mencke, Johann Burkhard',
    'Fennitzer, Georg',
    'Langenscheidt, Carl Georg Felix',
    'Millevoye, Charles Hubert',
    'Dilthey, Julius Friedrich Karl',
    'Peake, Robert',
    'Day, John',
    'Kay, John',
    'Kepler, Johannes',
    'Amthor, Eduard Gottlieb',
    'Lippincott, Joshua Ballinger',
    'Gebhardt, Johannes Martin',
    'Weber, Georg Christoph',
    'Rodd, Thomas',
    'Bauer, Johann Michael',
    'Baumann, Georg',
    'Koler, Johann',
    'Perthes, Wilhelm',
    'Brunet, Jacques-Charles',
    'Fauche-Borel, Louis',
    'Treuttel, Johann Georg',
    'Neumann, Ernst Leopold',
    'Endter, Johann Daniel',
    'Schellbach, Friedrich Julius',
    'Saugrain, Claude-Marin',
    'Borstell, Johannes Hermann Friedrich',
    'Biedermann, Karl',
    'Saugrain, Guillaume Claude',
    'Lochner, Leonhard Christophorus',
    'Homerus',
    'Overton, John',
    'Schloepke, H. G.',
    'Faust, Johannes',
    'Bauer, Andreas Friedrich',
    'Berger-Levrault, Oscar',
    'Hipparchus',
    'Wild, Heinrich',
    'Hallberger, Eduard',
    'Schrag, Georg Friedrich Heinrich',
    'Bodoni, Giambattista',
    'Calenius, Gerwin',
    'Mylius, Wilhelm Christhelf Siegmund',
    'Alexis, Willibald',
    'Winer, Georg Benedict',
    'Hofmeister, Friedrich',
    'Gutenberg, Johannes',
    'Manz, Georg Josef',
    'Pius',
    'Mariette, Jean',
    'Luchtmans, Johannes',
    'Morgenstern, Ernst',
    'Norel, Jan',
    'Leibing, Theodor',
    'Zschau, Johann Andreas',
    'Stoopius, Jacobus',
    'Leske, Carl Wilhelm',
    'Volkmann, Ludwig',
    'Hartwig, Konstantin',
    'Knorr, Thomas',
    'List, Felix',
    'Fraser, James',
    'Adelbulner, Johann Ernst',
    'Manuzio, Aldo',
    'Franck, Michael',
    'Schumacher von Marienfrid, Anton',
    'Tyroff, Margaretha',
    'Ungar, Karel Rafael',
]